apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  DATABASE_URL: "postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@postgresql:5432/{{ .Values.postgresql.database }}"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  BASE_DOMAIN: "{{ .Values.global.domain }}"
  NODE_ENV: "production"
  IN_CLUSTER: "true"
  PORT: "3000"
